component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/edu/.*
- ./bin/edu/rice/.*
- ./bin/edu/rice/cs/.*
- ./bin/edu/rice/cs/drjava/.*
- ./bin/edu/rice/cs/drjava/config/.*
- ./bin/edu/rice/cs/drjava/model/.*
- ./bin/edu/rice/cs/drjava/model/cache/.*
- ./bin/edu/rice/cs/drjava/model/compiler/.*
- ./bin/edu/rice/cs/drjava/model/debug/.*
- ./bin/edu/rice/cs/drjava/model/debug/jpda/.*
- ./bin/edu/rice/cs/drjava/model/definitions/.*
- ./bin/edu/rice/cs/drjava/model/definitions/indent/.*
- ./bin/edu/rice/cs/drjava/model/definitions/reducedmodel/.*
- ./bin/edu/rice/cs/drjava/model/javadoc/.*
- ./bin/edu/rice/cs/drjava/model/junit/.*
- ./bin/edu/rice/cs/drjava/model/print/.*
- ./bin/edu/rice/cs/drjava/model/repl/.*
- ./bin/edu/rice/cs/drjava/model/repl/newjvm/.*
- ./bin/edu/rice/cs/drjava/platform/.*
- ./bin/edu/rice/cs/drjava/project/.*
- ./bin/edu/rice/cs/drjava/ui/.*
- ./bin/edu/rice/cs/drjava/ui/avail/.*
- ./bin/edu/rice/cs/drjava/ui/config/.*
- ./bin/edu/rice/cs/drjava/ui/doc-files/.*
- ./bin/edu/rice/cs/drjava/ui/icons/.*
- ./bin/edu/rice/cs/drjava/ui/predictive/.*
- ./bin/edu/rice/cs/util/.*
- ./bin/edu/rice/cs/util/classloader/.*
- ./bin/edu/rice/cs/util/docnavigation/.*
- ./bin/edu/rice/cs/util/jar/.*
- ./bin/edu/rice/cs/util/newjvm/.*
- ./bin/edu/rice/cs/util/sexp/.*
- ./bin/edu/rice/cs/util/swing/.*
- ./bin/edu/rice/cs/util/text/.*
- ./lib/.*
